In [1]:
import pandas as pd;

In [19]:
data = {
"Name": ["Ram", "Shyam", "Ghanshyam"],
"Age": [28, 34, 22],
"Salary": [50000, 60000, 45000],
'SP': [2100,3000,5000],
'CP': [2000,2800,5000]
}

df = pd.DataFrame(data)
df

        Name  Age  Salary    SP    CP
0        Ram   28   50000  2100  2000
1      Shyam   34   60000  3000  2800
2  Ghanshyam   22   45000  5000  5000

In [20]:
df['Total_Cost'] = df['SP']*df['CP']
df

        Name  Age  Salary    SP    CP  Total_Cost
0        Ram   28   50000  2100  2000     4200000
1      Shyam   34   60000  3000  2800     8400000
2  Ghanshyam   22   45000  5000  5000    25000000

In [21]:
df['Diff'] = df['SP']-df['CP']
df

        Name  Age  Salary    SP    CP  Total_Cost  Diff
0        Ram   28   50000  2100  2000     4200000   100
1      Shyam   34   60000  3000  2800     8400000   200
2  Ghanshyam   22   45000  5000  5000    25000000     0

In [22]:
df['Prof_Loss'] = df['Diff'].apply(lambda x: 'Profit ' if x>0 else 'Loss')
df

        Name  Age  Salary    SP    CP  Total_Cost  Diff Prof_Loss
0        Ram   28   50000  2100  2000     4200000   100   Profit
1      Shyam   34   60000  3000  2800     8400000   200   Profit
2  Ghanshyam   22   45000  5000  5000    25000000     0      Loss