In [1]:
import pandas as pd;

In [25]:
data = {
"Name": ["Ram", "Shyam", "Ghanshyam",'Abram','Dam','Bing','Luicie','Wisky','Akhil',"AK", "BH", "KJ",'PL','IK','OY','WE','SQ','ML','AB','KL'],
"Age": [28, 34, 22,29,25,53,18,20,22,54,34,32,46,42,86,49,28,19,28,19],
"Salary": [50000, 60000, 45000,50000, 60000, 45000,50000, 60000, 45000,50000, 60000, 45000,50000, 60000, 45000,50000, 60000, 45000,35000,24000],
'Units': [10, 20, 15,10, 20, 15,10, 20, 15,10, 20, 15,10, 20, 15,10, 20, 15,23,16],
'SP': [2100,3000,5000,2100,3000,5000,2100,3000,5000,2100,3000,5000,2100,3000,5000,2100,3000,5000,2100,3000],
'CP': [2000,2800,5000,2000,2800,5000,2000,2800,5000,2000,2800,5000,2000,2800,5000,2000,2800,5000,2000,2800]
}

df = pd.DataFrame(data)
df

         Name  Age  Salary  Units    SP    CP
0         Ram   28   50000     10  2100  2000
1       Shyam   34   60000     20  3000  2800
2   Ghanshyam   22   45000     15  5000  5000
3       Abram   29   50000     10  2100  2000
4         Dam   25   60000     20  3000  2800
5        Bing   53   45000     15  5000  5000
6      Luicie   18   50000     10  2100  2000
7       Wisky   20   60000     20  3000  2800
8       Akhil   22   45000     15  5000  5000
9          AK   54   50000     10  2100  2000
10         BH   34   60000     20  3000  2800
11         KJ   32   45000     15  5000  5000
12         PL   46   50000     10  2100  2000
13         IK   42   60000     20  3000  2800
14         OY   86   45000     15  5000  5000
15         WE   49   50000     10  2100  2000
16         SQ   28   60000     20  3000  2800
17         ML   19   45000     15  5000  5000
18         AB   28   35000     23  2100  2000
19         KL   19   24000     16  3000  2800

In [26]:
df['Total_Cost'] = df['SP']*df['CP']
df

         Name  Age  Salary  Units    SP    CP  Total_Cost
0         Ram   28   50000     10  2100  2000     4200000
1       Shyam   34   60000     20  3000  2800     8400000
2   Ghanshyam   22   45000     15  5000  5000    25000000
3       Abram   29   50000     10  2100  2000     4200000
4         Dam   25   60000     20  3000  2800     8400000
5        Bing   53   45000     15  5000  5000    25000000
6      Luicie   18   50000     10  2100  2000     4200000
7       Wisky   20   60000     20  3000  2800     8400000
8       Akhil   22   45000     15  5000  5000    25000000
9          AK   54   50000     10  2100  2000     4200000
10         BH   34   60000     20  3000  2800     8400000
11         KJ   32   45000     15  5000  5000    25000000
12         PL   46   50000     10  2100  2000     4200000
13         IK   42   60000     20  3000  2800     8400000
14         OY   86   45000     15  5000  5000    25000000
15         WE   49   50000     10  2100  2000     4200000
16         SQ   28   60000     20  3000  2800     8400000
17         ML   19   45000     15  5000  5000    25000000
18         AB   28   35000     23  2100  2000     4200000
19         KL   19   24000     16  3000  2800     8400000

In [27]:
df['Diff'] = df['SP']-df['CP']
df

         Name  Age  Salary  Units    SP    CP  Total_Cost  Diff
0         Ram   28   50000     10  2100  2000     4200000   100
1       Shyam   34   60000     20  3000  2800     8400000   200
2   Ghanshyam   22   45000     15  5000  5000    25000000     0
3       Abram   29   50000     10  2100  2000     4200000   100
4         Dam   25   60000     20  3000  2800     8400000   200
5        Bing   53   45000     15  5000  5000    25000000     0
6      Luicie   18   50000     10  2100  2000     4200000   100
7       Wisky   20   60000     20  3000  2800     8400000   200
8       Akhil   22   45000     15  5000  5000    25000000     0
9          AK   54   50000     10  2100  2000     4200000   100
10         BH   34   60000     20  3000  2800     8400000   200
11         KJ   32   45000     15  5000  5000    25000000     0
12         PL   46   50000     10  2100  2000     4200000   100
13         IK   42   60000     20  3000  2800     8400000   200
14         OY   86   45000     15  5000  5000    25000000     0
15         WE   49   50000     10  2100  2000     4200000   100
16         SQ   28   60000     20  3000  2800     8400000   200
17         ML   19   45000     15  5000  5000    25000000     0
18         AB   28   35000     23  2100  2000     4200000   100
19         KL   19   24000     16  3000  2800     8400000   200

In [39]:
df['Prof_Loss'] = df['Diff'].apply(lambda x: 'Profit ' if x>0 else 'Loss')
df

,Name,Age,Salary,Units,SP,CP,Total_Cost,Diff,Prof_Loss,Bulk_Order
0,Ram,28,50000,10,2100,2000,4200000,100,Profit,not
1,Shyam,34,60000,20,3000,2800,8400000,200,Profit,Bulk
2,Ghanshyam,22,45000,15,5000,5000,25000000,0,Loss,Bulk
3,Abram,29,50000,10,2100,2000,4200000,100,Profit,not
4,Dam,25,60000,20,3000,2800,8400000,200,Profit,Bulk
5,Bing,53,45000,15,5000,5000,25000000,0,Loss,Bulk
6,Luicie,18,50000,10,2100,2000,4200000,100,Profit,not
7,Wisky,20,60000,20,3000,2800,8400000,200,Profit,Bulk
8,Akhil,22,45000,15,5000,5000,25000000,0,Loss,Bulk
9,AK,54,50000,10,2100,2000,4200000,100,Profit,not
10,BH,34,60000,20,3000,2800,8400000,200,Profit,Bulk
11,KJ,32,45000,15,5000,5000,25000000,0,Loss,Bulk
12,PL,46,50000,10,2100,2000,4200000,100,Profit,not
13,IK,42,60000,20,3000,2800,8400000,200,Profit,Bulk
14,OY,86,45000,15,5000,5000,25000000,0,Loss,Bulk
15,WE,49,50000,10,2100,2000,4200000,100,Profit,not
16,SQ,28,60000,20,3000,2800,8400000,200,Profit,Bulk
17,ML,19,45000,15,5000,5000,25000000,0,Loss,Bulk
18,AB,28,35000,23,2100,2000,4200000,100,Profit,Bulk
19,KL,19,24000,16,3000,2800,8400000,200,Profit,Bulk

In [40]:
df['Bulk_Order'] = df['Units'].apply(lambda x: 'Bulk ' if x>10 else 'not')
df

,Name,Age,Salary,Units,SP,CP,Total_Cost,Diff,Prof_Loss,Bulk_Order
0,Ram,28,50000,10,2100,2000,4200000,100,Profit,not
1,Shyam,34,60000,20,3000,2800,8400000,200,Profit,Bulk
2,Ghanshyam,22,45000,15,5000,5000,25000000,0,Loss,Bulk
3,Abram,29,50000,10,2100,2000,4200000,100,Profit,not
4,Dam,25,60000,20,3000,2800,8400000,200,Profit,Bulk
5,Bing,53,45000,15,5000,5000,25000000,0,Loss,Bulk
6,Luicie,18,50000,10,2100,2000,4200000,100,Profit,not
7,Wisky,20,60000,20,3000,2800,8400000,200,Profit,Bulk
8,Akhil,22,45000,15,5000,5000,25000000,0,Loss,Bulk
9,AK,54,50000,10,2100,2000,4200000,100,Profit,not
10,BH,34,60000,20,3000,2800,8400000,200,Profit,Bulk
11,KJ,32,45000,15,5000,5000,25000000,0,Loss,Bulk
12,PL,46,50000,10,2100,2000,4200000,100,Profit,not
13,IK,42,60000,20,3000,2800,8400000,200,Profit,Bulk
14,OY,86,45000,15,5000,5000,25000000,0,Loss,Bulk
15,WE,49,50000,10,2100,2000,4200000,100,Profit,not
16,SQ,28,60000,20,3000,2800,8400000,200,Profit,Bulk
17,ML,19,45000,15,5000,5000,25000000,0,Loss,Bulk
18,AB,28,35000,23,2100,2000,4200000,100,Profit,Bulk
19,KL,19,24000,16,3000,2800,8400000,200,Profit,Bulk